#!/usr/bin/env python3
"""Generate a CSV of supported chip names per DSA driver row.

The script consumes a transposed driver-first CSV generated by
scripts/generate_dsa_feature_matrix.py and resolves each driver row back to
Linux/OpenWrt source files. It then extracts supported chip names from chip
tables, device-tree match tables, bus-specific device ID tables, and chip-ID
macros.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import DefaultDict, Dict, Iterable, List, Sequence, Set, Tuple


DRIVERS_REL = Path("drivers/net/dsa")
OPENWRT_PATCH_ROOT_REL = Path("target/linux")
DEVICE_TABLE_STRUCTS = {
    "of_device_id",
    "i2c_device_id",
    "spi_device_id",
    "mdio_device_id",
    "platform_device_id",
}
DEVICE_SUFFIXES = (
    "-switch",
    "_switch",
    "-smi",
    "_smi",
    "-mdio",
    "_mdio",
    "-spi",
    "_spi",
    "-i2c",
    "_i2c",
    "-srab",
    "_srab",
    "-mmap",
    "_mmap",
)


def extract_documented_chip_names(text: str) -> Set[str]:
    """Extract chip names from C comment bullet lists.

    This captures patterns commonly used in driver headers such as:
      *  - RTL8365MB-VC
    """
    names: Set[str] = set()
    for comment_body in re.findall(r"/\*.*?\*/", text, flags=re.S):
        for raw_name in re.findall(r"^\s*\*\s*-\s*([A-Z0-9][A-Z0-9-]+)\s*$", comment_body, flags=re.M):
            name = raw_name.strip().strip(".,;:")
            # Keep only chip-like tokens to avoid unrelated list entries.
            if any(ch.isdigit() for ch in name):
                names.add(name)
    return names


def strip_c_comments(text: str) -> str:
    """Remove C // and /* */ comments while preserving literals."""
    out: List[str] = []
    i = 0
    n = len(text)
    in_line_comment = False
    in_block_comment = False
    in_string = False
    in_char = False

    while i < n:
        c = text[i]
        nxt = text[i + 1] if i + 1 < n else ""

        if in_line_comment:
            if c == "\n":
                in_line_comment = False
                out.append(c)
            i += 1
            continue

        if in_block_comment:
            if c == "*" and nxt == "/":
                in_block_comment = False
                i += 2
            else:
                if c == "\n":
                    out.append(c)
                i += 1
            continue

        if in_string:
            out.append(c)
            if c == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 2
                continue
            if c == '"':
                in_string = False
            i += 1
            continue

        if in_char:
            out.append(c)
            if c == "\\" and i + 1 < n:
                out.append(text[i + 1])
                i += 2
                continue
            if c == "'":
                in_char = False
            i += 1
            continue

        if c == "/" and nxt == "/":
            in_line_comment = True
            i += 2
            continue

        if c == "/" and nxt == "*":
            in_block_comment = True
            i += 2
            continue

        if c == '"':
            in_string = True
            out.append(c)
            i += 1
            continue

        if c == "'":
            in_char = True
            out.append(c)
            i += 1
            continue

        out.append(c)
        i += 1

    return "".join(out)


def find_matching_brace(text: str, open_brace_pos: int) -> int:
    """Return index of the closing brace matching text[open_brace_pos]."""
    if open_brace_pos < 0 or open_brace_pos >= len(text) or text[open_brace_pos] != "{":
        raise ValueError("open_brace_pos must point to '{'")

    depth = 0
    i = open_brace_pos
    while i < len(text):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1

    raise ValueError("no matching closing brace found")


def get_linux_version(linux_root: Path) -> str:
    """Extract Linux kernel version from Makefile."""
    makefile = linux_root / "Makefile"
    if not makefile.is_file():
        return "unknown"

    text = makefile.read_text(encoding="utf-8", errors="ignore")
    version = None
    patchlevel = None
    sublevel = None

    for line in text.split("\n")[:30]:
        if line.startswith("VERSION"):
            match = re.search(r"=\s*(\d+)", line)
            if match:
                version = match.group(1)
        elif line.startswith("PATCHLEVEL"):
            match = re.search(r"=\s*(\d+)", line)
            if match:
                patchlevel = match.group(1)
        elif line.startswith("SUBLEVEL"):
            match = re.search(r"=\s*(\d+)", line)
            if match:
                sublevel = match.group(1)

    if version and patchlevel and sublevel:
        return f"{version}.{patchlevel}.{sublevel}"
    return "unknown"


def get_openwrt_version(openwrt_root: Path) -> str:
    """Extract OpenWrt version from git HEAD or VERSION file."""
    git_head = openwrt_root / ".git" / "HEAD"
    if git_head.is_file():
        try:
            head_content = git_head.read_text(encoding="utf-8", errors="ignore").strip()
            if head_content.startswith("ref:"):
                ref_path = head_content.split(":", 1)[1].strip()
                ref_file = openwrt_root / ".git" / ref_path
                if ref_file.is_file():
                    commit = ref_file.read_text(encoding="utf-8", errors="ignore").strip()[:7]
                    return f"git:{commit}"
            elif len(head_content) >= 7:
                return f"git:{head_content[:7]}"
        except Exception:
            pass

    version_file = openwrt_root / "VERSION"
    if version_file.is_file():
        content = version_file.read_text(encoding="utf-8", errors="ignore").strip()
        if content:
            return content

    version_mk = openwrt_root / "include" / "version.mk"
    if version_mk.is_file():
        text = version_mk.read_text(encoding="utf-8", errors="ignore")
        match = re.search(r"VERSION_NUMBER:=\$\(if\s+\$\(VERSION_NUMBER\),\$\(VERSION_NUMBER\),([^\)]+)\)", text)
        if match:
            inferred = match.group(1).strip()
            if inferred:
                return inferred

    return "unknown"


def current_utc_timestamp() -> str:
    """Return an ISO-8601 UTC timestamp for metadata comments."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def load_driver_rows(csv_path: Path) -> Tuple[List[str], str | None, str | None]:
    """Load ordered driver rows and metadata from a transposed feature matrix CSV."""
    linux_version = None
    openwrt_version = None
    drivers: List[str] = []
    header_seen = False

    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.reader(handle)
        for row in reader:
            if not row:
                continue

            first = row[0].strip()
            if not first:
                continue

            if first.startswith("# Linux:"):
                linux_version = first.split(":", 1)[1].strip()
                continue

            if first.startswith("# OpenWrt:"):
                openwrt_version = first.split(":", 1)[1].strip()
                continue

            if first.startswith("#"):
                continue

            if not header_seen:
                if first != "driver":
                    raise ValueError(
                        f"input CSV must be transposed with 'driver' as the first header cell, got: {first!r}"
                    )
                header_seen = True
                continue

            drivers.append(first)

    if not header_seen:
        raise ValueError("input CSV is missing a transposed driver header row")

    return drivers, linux_version, openwrt_version


def iter_linux_dsa_sources(linux_root: Path) -> Iterable[Tuple[str, Path]]:
    """Yield normalized Linux DSA driver source paths."""
    drivers_dir = linux_root / DRIVERS_REL
    if not drivers_dir.is_dir():
        return []

    return [
        (c_file.relative_to(linux_root).as_posix(), c_file)
        for c_file in sorted(drivers_dir.rglob("*.c"))
    ]


def iter_openwrt_dsa_sources(openwrt_root: Path) -> List[Tuple[str, Path]]:
    """Yield normalized OpenWrt DSA driver source paths from files and files-* directories."""
    patch_root = openwrt_root / OPENWRT_PATCH_ROOT_REL
    if not patch_root.is_dir():
        return []

    results: List[Tuple[str, Path]] = []
    for c_file in sorted(patch_root.rglob("*.c")):
        try:
            rel_to_root = c_file.relative_to(patch_root)
        except ValueError:
            continue

        if not any(part == "files" or part.startswith("files-") for part in rel_to_root.parts):
            continue

        try:
            drivers_idx = rel_to_root.parts.index("drivers")
        except ValueError:
            continue

        normalized = "/".join(rel_to_root.parts[drivers_idx:])
        if normalized.startswith("drivers/net/dsa/"):
            results.append((normalized, c_file))

    return results


def build_source_index(entries: Iterable[Tuple[str, Path]]) -> Tuple[Dict[str, List[Path]], Dict[str, List[Path]]]:
    """Build indexes by normalized path and basename."""
    by_path: DefaultDict[str, List[Path]] = defaultdict(list)
    by_basename: DefaultDict[str, List[Path]] = defaultdict(list)

    for normalized, path in entries:
        by_path[normalized].append(path)
        by_basename[path.name].append(path)

    return dict(by_path), dict(by_basename)


def parse_patch_target_path(diff_header_line: str) -> str:
    """Extract normalized file path from a unified diff +++ line."""
    value = diff_header_line[4:].strip()
    if value == "/dev/null":
        return ""
    if value.startswith("a/") or value.startswith("b/"):
        return value[2:]
    return value


def collect_openwrt_patch_target_texts(openwrt_root: Path) -> Dict[str, str]:
    """Collect non-removed patch hunk text per target file for OpenWrt patches."""
    patch_root = openwrt_root / OPENWRT_PATCH_ROOT_REL
    if not patch_root.is_dir():
        return {}

    collected: DefaultDict[str, List[str]] = defaultdict(list)
    for patch_file in sorted(patch_root.rglob("*.patch")):
        current_target = ""
        in_hunk = False
        for raw_line in patch_file.read_text(encoding="utf-8", errors="ignore").splitlines():
            if raw_line.startswith("+++"):
                current_target = parse_patch_target_path(raw_line)
                in_hunk = False
                continue

            if raw_line.startswith("@@"):
                in_hunk = True
                continue

            if not in_hunk or not current_target.startswith("drivers/net/dsa/"):
                continue

            if not raw_line or raw_line[0] not in (" ", "+"):
                continue
            if raw_line.startswith("+++") or raw_line.startswith("---"):
                continue

            collected[current_target].append(raw_line[1:])

    return {target: "\n".join(lines) for target, lines in collected.items()}


def extract_normalized_driver_path(driver_key: str) -> Tuple[bool, str | None]:
    """Return (is_openwrt, normalized_path_or_basename)."""
    is_openwrt = driver_key.startswith("openwrt:")
    body = driver_key[8:] if is_openwrt else driver_key
    match = re.search(r"(drivers/net/dsa/.+?\.c)", body)
    if match:
        return is_openwrt, match.group(1)

    if body.endswith(".c"):
        return is_openwrt, Path(body).name

    return is_openwrt, None


def companion_normalized_paths(normalized_path: str, available_paths: Iterable[str]) -> List[str]:
    """Return likely companion files for family drivers."""
    basename = Path(normalized_path).name
    parent = str(Path(normalized_path).parent)
    candidates: List[str] = []

    if basename == "b53_common.c":
        candidates.extend(
            path for path in available_paths if path.startswith(f"{parent}/b53_") and path.endswith(".c")
        )
    elif basename == "mt7530.c":
        candidates.extend(
            path
            for path in available_paths
            if path.startswith(f"{parent}/mt7530-") and path.endswith(".c")
        )
    elif basename == "ksz_common.c":
        candidates.extend(
            path
            for path in available_paths
            if path.startswith(f"{parent}/")
            and Path(path).name.endswith(".c")
            and (Path(path).name.startswith("ksz") or Path(path).name.startswith("lan"))
        )
    elif basename == "lantiq_gswip_common.c":
        candidates.extend(
            path
            for path in available_paths
            if path in {f"{parent}/lantiq_gswip.c", f"{parent}/mxl-gsw1xx.c"}
        )
    elif basename == "felix.c":
        candidates.extend(
            path
            for path in available_paths
            if path.startswith(f"{parent}/felix_")
            or path.startswith(f"{parent}/seville_")
            or path == f"{parent}/ocelot_ext.c"
        )
    elif basename == "xrs700x.c":
        candidates.extend(
            path
            for path in available_paths
            if path.startswith(f"{parent}/xrs700x_") and path.endswith(".c")
        )
    elif basename == "dsa.c" and "/rtl83xx" in normalized_path:
        candidates.extend(
            path
            for path in available_paths
            if path.startswith(f"{parent}/rtl") and path.endswith(".c") and path != normalized_path
        )
    elif basename.endswith("-core.c"):
        prefix = basename[: -len("-core.c")]
        candidates.extend(
            path
            for path in available_paths
            if path.startswith(f"{parent}/{prefix}") and path.endswith(".c")
        )

    candidates = [path for path in candidates if path != normalized_path]
    return sorted(dict.fromkeys(candidates))


def normalize_device_name(raw_name: str) -> str:
    """Normalize a DT compatible or device-id string into a readable chip token."""
    value = raw_name.strip()
    if not value:
        return ""

    if "," in value:
        value = value.split(",", 1)[1]

    for suffix in DEVICE_SUFFIXES:
        if value.endswith(suffix):
            value = value[: -len(suffix)]
            break

    value = value.replace("_", "-")
    return value.upper()


def natural_sort_key(value: str) -> List[object]:
    """Sort mixed alpha-numeric names predictably."""
    parts = re.split(r"(\d+)", value)
    key: List[object] = []
    for part in parts:
        if part.isdigit():
            key.append(int(part))
        else:
            key.append(part.lower())
    return key


def extract_struct_arrays(cleaned_text: str) -> List[Tuple[str, str, str]]:
    """Return (struct_name, var_name, body) for top-level struct arrays."""
    pattern = re.compile(
        r"(?:^|[;\n])\s*(?:static\s+)?(?:const\s+)?struct\s+"
        r"([A-Za-z_][A-Za-z0-9_]*)\s+([A-Za-z_][A-Za-z0-9_]*)\s*"
        r"\[[^\]]*\]\s*=\s*\{",
        flags=re.M,
    )

    arrays: List[Tuple[str, str, str]] = []
    for match in pattern.finditer(cleaned_text):
        open_brace = cleaned_text.find("{", match.end() - 1)
        if open_brace == -1:
            continue
        try:
            close_brace = find_matching_brace(cleaned_text, open_brace)
        except ValueError:
            continue
        arrays.append((match.group(1), match.group(2), cleaned_text[open_brace + 1 : close_brace]))

    return arrays


def extract_struct_objects(cleaned_text: str) -> List[Tuple[str, str, str]]:
    """Return (struct_name, var_name, body) for top-level struct objects."""
    pattern = re.compile(
        r"(?:^|[;\n])\s*(?:static\s+)?(?:const\s+)?struct\s+"
        r"([A-Za-z_][A-Za-z0-9_]*)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*\{",
        flags=re.M,
    )

    objects: List[Tuple[str, str, str]] = []
    for match in pattern.finditer(cleaned_text):
        open_brace = cleaned_text.find("{", match.end() - 1)
        if open_brace == -1:
            continue
        try:
            close_brace = find_matching_brace(cleaned_text, open_brace)
        except ValueError:
            continue
        objects.append((match.group(1), match.group(2), cleaned_text[open_brace + 1 : close_brace]))

    return objects


def infer_name_from_symbol(var_name: str) -> str:
    """Infer a chip token from a symbol such as felix_info_vsc9959."""
    parts = [part for part in var_name.split("_") if part]
    generic = {"info", "chip", "variant", "data", "match", "table", "driver", "ops", "felix", "seville"}
    for part in reversed(parts):
        lowered = part.lower()
        if lowered in generic:
            continue
        if any(ch.isdigit() for ch in part):
            return part.upper()
    return ""


def extract_chip_candidates_from_text(text: str) -> Tuple[Set[str], Set[str], Set[str]]:
    """Extract (explicit_names, compat_names, fallback_id_names) from source text."""
    cleaned = strip_c_comments(text)
    explicit_names: Set[str] = set()
    compat_names: Set[str] = set()
    fallback_names: Set[str] = set()

    # Some drivers document the family chip list in header comments.
    explicit_names.update(extract_documented_chip_names(text))

    for struct_name, var_name, body in extract_struct_arrays(cleaned):
        lower_name = f"{struct_name} {var_name}".lower()

        if struct_name in DEVICE_TABLE_STRUCTS:
            for compatible in re.findall(r'\.compatible\s*=\s*"([^"]+)"', body):
                normalized = normalize_device_name(compatible)
                if normalized:
                    compat_names.add(normalized)

            if struct_name in {"i2c_device_id", "spi_device_id", "platform_device_id"}:
                for device_id in re.findall(r'\{\s*"([^"]+)"', body):
                    normalized = normalize_device_name(device_id)
                    if normalized:
                        compat_names.add(normalized)
            continue

        looks_like_chip_table = any(
            token in lower_name for token in ("chip", "info", "switch", "variant", "table")
        ) or any(token in body for token in (".chip_id", ".prod_num", ".dev_name", ".compatible"))
        if not looks_like_chip_table:
            continue

        for name in re.findall(r'\.(?:dev_name|name)\s*=\s*"([^"]+)"', body):
            normalized = name.strip()
            if normalized:
                explicit_names.add(normalized)

        for compatible in re.findall(r'\.compatible\s*=\s*"([^"]+)"', body):
            normalized = normalize_device_name(compatible)
            if normalized:
                compat_names.add(normalized)

    for struct_name, var_name, body in extract_struct_objects(cleaned):
        lower_var_name = var_name.lower()
        symbol_is_candidate = (
            lower_var_name.endswith("_info")
            or "_info_" in lower_var_name
            or lower_var_name.endswith("_variant")
        )
        if not symbol_is_candidate:
            continue

        inferred_name = infer_name_from_symbol(var_name)
        if inferred_name:
            fallback_names.add(inferred_name)

        if any(token in body for token in (".chip_id", ".prod_num", ".dev_name")):
            for name in re.findall(r'\.(?:dev_name|name)\s*=\s*"([^"]+)"', body):
                normalized = name.strip()
                if normalized:
                    explicit_names.add(normalized)

    for macro_name in re.findall(
        r"\b([A-Z0-9]+(?:[A-Z0-9_]*[A-Z0-9])?)_(?:CHIP|DEVICE|FAMILY)_ID\b",
        cleaned,
    ):
        if any(token in macro_name for token in ("REG", "MASK", "SHIFT", "TABLE", "PORT")):
            continue
        fallback_names.add(macro_name.replace("_", "-"))

    return explicit_names, compat_names, fallback_names


def select_chip_names(explicit_names: Set[str], compat_names: Set[str], fallback_names: Set[str]) -> List[str]:
    """Choose the most specific extracted names while keeping deterministic order."""
    if explicit_names:
        return sorted(explicit_names, key=natural_sort_key)
    if compat_names:
        return sorted(compat_names | fallback_names, key=natural_sort_key)
    return sorted(fallback_names, key=natural_sort_key)


def resolve_driver_texts(
    driver_key: str,
    linux_by_path: Dict[str, List[Path]],
    linux_by_basename: Dict[str, List[Path]],
    openwrt_by_path: Dict[str, List[Path]],
    openwrt_by_basename: Dict[str, List[Path]],
    openwrt_patch_texts: Dict[str, str],
) -> Tuple[List[str], List[str]]:
    """Return candidate source texts and resolution warnings for one driver key."""
    warnings: List[str] = []
    texts: List[str] = []
    is_openwrt, normalized_or_basename = extract_normalized_driver_path(driver_key)
    if not normalized_or_basename:
        return [], [f"{driver_key}: could not determine source path from driver key"]

    paths: List[Path] = []
    linux_keys = linux_by_path.keys()
    openwrt_keys = openwrt_by_path.keys()

    if normalized_or_basename.startswith("drivers/net/dsa/"):
        if is_openwrt:
            paths.extend(openwrt_by_path.get(normalized_or_basename, []))
            paths.extend(linux_by_path.get(normalized_or_basename, []))
            for companion in companion_normalized_paths(normalized_or_basename, openwrt_keys):
                paths.extend(openwrt_by_path.get(companion, []))
            for companion in companion_normalized_paths(normalized_or_basename, linux_keys):
                paths.extend(linux_by_path.get(companion, []))
            patch_text = openwrt_patch_texts.get(normalized_or_basename)
            if patch_text:
                texts.append(patch_text)
        else:
            paths.extend(linux_by_path.get(normalized_or_basename, []))
            for companion in companion_normalized_paths(normalized_or_basename, linux_keys):
                paths.extend(linux_by_path.get(companion, []))
    else:
        path_index = openwrt_by_basename if is_openwrt else linux_by_basename
        matches = path_index.get(normalized_or_basename, [])
        if len(matches) > 1:
            warnings.append(
                f"{driver_key}: basename-only resolution is ambiguous ({len(matches)} candidates)"
            )
        paths.extend(matches)

    unique_paths: List[Path] = []
    seen_paths: Set[Path] = set()
    for path in paths:
        if path in seen_paths:
            continue
        seen_paths.add(path)
        unique_paths.append(path)

    for path in unique_paths:
        try:
            texts.append(path.read_text(encoding="utf-8", errors="ignore"))
        except OSError as exc:
            warnings.append(f"{driver_key}: failed to read {path}: {exc}")

    if not texts:
        warnings.append(f"{driver_key}: no candidate source text found")

    return texts, warnings


def write_chip_csv(
    out_path: Path,
    driver_rows: Sequence[str],
    chip_map: Dict[str, Sequence[str]],
    linux_version: str | None,
    openwrt_version: str | None,
    chip_delimiter: str,
) -> None:
    """Write the driver->chips CSV with metadata comments."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        if linux_version:
            writer.writerow([f"# Linux: {linux_version}"])
        if openwrt_version:
            writer.writerow([f"# OpenWrt: {openwrt_version}"])
        writer.writerow([f"# Generated: {current_utc_timestamp()}"])
        writer.writerow([])
        writer.writerow(["driver", "chips"])
        for driver in driver_rows:
            chips = chip_map.get(driver, [])
            writer.writerow([driver, chip_delimiter.join(chips)])


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=Path("dsa_feature_matrix.csv"),
        help="Path to the transposed feature-matrix CSV (default: ./dsa_feature_matrix.csv)",
    )
    parser.add_argument(
        "--linux-root",
        type=Path,
        default=Path("linux"),
        help="Path to Linux source root (default: ./linux)",
    )
    parser.add_argument(
        "--openwrt-root",
        type=Path,
        default=Path("openwrt"),
        help="Path to OpenWrt source root (default: ./openwrt)",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("dsa_driver_chip_list.csv"),
        help="Output CSV path (default: ./dsa_driver_chip_list.csv)",
    )
    parser.add_argument(
        "--chip-delimiter",
        default="; ",
        help="Delimiter used inside the chips column (default: '; ')",
    )
    parser.add_argument(
        "--warn-unresolved",
        action="store_true",
        help="Print warnings for unresolved or ambiguous driver rows",
    )
    parser.add_argument(
        "--openwrt-version",
        default=None,
        help="Optional OpenWrt version string override for CSV metadata",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str]) -> int:
    args = parse_args(argv)
    input_csv = args.input_csv.resolve()
    linux_root = args.linux_root.resolve()
    openwrt_root = args.openwrt_root.resolve()

    if not input_csv.is_file():
        print(f"error: input CSV not found: {input_csv}", file=sys.stderr)
        return 1

    driver_rows, csv_linux_version, csv_openwrt_version = load_driver_rows(input_csv)
    has_openwrt_rows = any(row.startswith("openwrt:") for row in driver_rows)
    linux_version = get_linux_version(linux_root) if linux_root.is_dir() else csv_linux_version
    openwrt_version = None
    if has_openwrt_rows:
        if args.openwrt_version:
            openwrt_version = args.openwrt_version
        elif openwrt_root.is_dir():
            openwrt_version = get_openwrt_version(openwrt_root)
        else:
            openwrt_version = csv_openwrt_version

    linux_entries = list(iter_linux_dsa_sources(linux_root))
    openwrt_entries = iter_openwrt_dsa_sources(openwrt_root)
    linux_by_path, linux_by_basename = build_source_index(linux_entries)
    openwrt_by_path, openwrt_by_basename = build_source_index(openwrt_entries)
    openwrt_patch_texts = collect_openwrt_patch_target_texts(openwrt_root)

    chip_map: Dict[str, List[str]] = {}
    unresolved: List[str] = []
    warnings: List[str] = []

    for driver_key in driver_rows:
        texts, resolution_warnings = resolve_driver_texts(
            driver_key,
            linux_by_path,
            linux_by_basename,
            openwrt_by_path,
            openwrt_by_basename,
            openwrt_patch_texts,
        )
        warnings.extend(resolution_warnings)

        explicit_names: Set[str] = set()
        compat_names: Set[str] = set()
        fallback_names: Set[str] = set()
        for text in texts:
            explicit, compat, fallback = extract_chip_candidates_from_text(text)
            explicit_names.update(explicit)
            compat_names.update(compat)
            fallback_names.update(fallback)

        chip_names = select_chip_names(explicit_names, compat_names, fallback_names)
        chip_map[driver_key] = chip_names
        if not chip_names:
            unresolved.append(driver_key)

    out_path = args.out
    if not out_path.is_absolute():
        out_path = Path.cwd() / out_path

    write_chip_csv(
        out_path,
        driver_rows,
        chip_map,
        linux_version,
        openwrt_version,
        args.chip_delimiter,
    )

    resolved = len(driver_rows) - len(unresolved)
    print(
        f"wrote {out_path} | drivers={len(driver_rows)} resolved={resolved} unresolved={len(unresolved)}"
    )

    if args.warn_unresolved:
        for message in warnings:
            print(f"warning: {message}", file=sys.stderr)
        for driver_key in unresolved:
            print(f"warning: {driver_key}: no chip names extracted", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))